import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {PiScript} from "@/lib/pi-network/sdk";
import Header from "@/components/header";
import Footer from "@/components/footer";
import {UserProvider} from "@/app/context/use-user";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <UserProvider>
          <Header />
          <div className="min-h-screen">
              {children}
          </div>
          <Footer />

          <PiScript />
          </UserProvider>
      </body>
    </html>
  );
}
